### ISSUE TITLE
Tracking issue: test coverage

### ISSUE THREAD

**Issue by Thomasdezeeuw** [rust-lang/socket2#156]
Current list left to test:

* [ ] `Socket::peer_addr`
* [ ] `Socket::try_clone`
* [ ] `Socket::shutdown`
* [ ] `Socket::recv_out_of_band`
* [ ] `Socket::peek`
* [ ] `Socket::recv_from`
* [ ] `Socket::peek_from`
* [ ] `Socket::send_out_of_band`
* [ ] `Socket::take_error`
* [ ] `Socket::write_timeout`
* [ ] `Socket::set_linger(None)`
* [ ] `Socket::join_multicast_v4`
* [ ] `Socket::leave_multicast_v4`
* [ ] `Socket::multicast_if_v4`
* [ ] `Socket::set_multicast_if_v4`
* [ ] `Socket::multicast_loop_v4`
* [ ] `Socket::set_multicast_loop_v4`
* [ ] `Socket::multicast_ttl_v4`
* [ ] `Socket::set_multicast_ttl_v4`
* [ ] `Socket::join_multicast_v6`
* [ ] `Socket::leave_multicast_v6`
* [ ] `Socket::multicast_hops_v6`
* [ ] `Socket::set_multicast_hops_v6`
* [ ] `Socket::multicast_if_v6`
* [ ] `Socket::set_multicast_if_v6`
* [ ] `Socket::multicast_loop_v6`
* [ ] `Socket::set_multicast_loop_v6`
* [ ] `Socket::read_vectored`
* [ ] `&Socket::read`
* [ ] `&Socket::read_vectored`
* [ ] `Socket::write_vectored`
* [ ] `Socket::flush`
* [ ] `&Socket::write`
* [ ] `&Socket::write_vectored`
* [ ] `&Socket::flush`
* [ ] `Socket::debug`
* [ ] `SockAddr::debug`

**Comment by Thomasdezeeuw** [comment]
I think we got pretty decent coverage now, closing this instead of keeping it open for ever.
