### ISSUE TITLE
Tracking issue: expand CI testing

### ISSUE THREAD

**Issue by Thomasdezeeuw** [rust-lang/socket2#78]
CI support, following the same tiers as rust (https://doc.rust-lang.org/nightly/rustc/platform-support.html).

## Tier 1

Tests must pass.

 * [x] Linux: tested.
 * [x] Windows: tested.
 * [x] macOS: tested.

## Tier 2

Must build.

 * [x] Android: check only.
 * [x] FreeBSD: check only.
 * [x] Fuchsia: check only.
 * [x] NetBSD: check only.
 * [x] Redox: check using Rust nightly only, stable is tracked here: https://github.com/rust-lang/socket2/issues/181.
 * [x] Solaris: check only.
 * [x] iOS: check only.
 * [x] illumos: check only.

## Tier 3

Best effort.

 * [ ] Haiku
 * [ ] Hermit
 * [ ] OpenBSD
 * [ ] VxWorks
 * [ ] DragonFly BSD

<hr>

Old description:

Currently only Linux, macOS and Windows are tested on the CI but we support (to some degree) many more OSes. We should add more of these OSes to the CI, at least running `cargo check`. For (Rust) tier 1 architecture/OS combos this should be easy, but for other tiers `rustup` might not be supported.

**Comment by KodrAus** [comment]
cc @rust-lang/infra I think we have a few repos in `rust-lang` with fairly extensive CI suites. Can we think of any examples that we could use to bootstrap some broader CI here? I'm thinking particularly of iOS...

**Comment by Thomasdezeeuw** [comment]
@KodrAus, @rust-lang/infra a little update: tier 2 targets are now all `cargo check`ed, but if it's possible to actually run the tests somehow I would prefer that.

**Comment by KodrAus** [comment]
@Thomasdezeeuw I'm guessing it's more the OS than the architecture that you're interested in for the tier 2 targets?

It looks like we might be able to [use MacOS workers in GitHub Actions to run some of the BSDs](https://github.com/vmactions/freebsd-vm). Alternatively, Travis CI does seem to support FreeBSD (although I can't find any docs on it), which we do still use in some repos here in `rust-lang` (specifically `stdarch` and `stdsimd`).

**Comment by Thomasdezeeuw** [comment]
> @Thomasdezeeuw I'm guessing it's more the OS than the architecture that you're interested in for the tier 2 targets?

Yes let's start with the OS. I think if we can run tests on all supported OSs, on any architecture, we can ensure the functionally works. Than `cargo check` would be enough for different architectures just to make the we got the `libc` definitions and functions right.

> It looks like we might be able to [use MacOS workers in GitHub Actions to run some of the BSDs](https://github.com/vmactions/freebsd-vm). Alternatively, Travis CI does seem to support FreeBSD (although I can't find any docs on it), which we do still use in some repos here in `rust-lang` (specifically `stdarch` and `stdsimd`).

There is also https://cirrus-ci.org/ for FreeBSD, e.g. Mio uses the following file: https://github.com/tokio-rs/mio/blob/04050dbd87d7b79c33168c6a972a8bb35cf510f8/.cirrus.yml.

**Comment by Thomasdezeeuw** [comment]
Don't think there is much left to do here, so closing.

**Comment by jkelleyrtp** [comment]
I believe WASI can be supported since their lib-c exposes sockets. I'd be interested in adding it.

**Comment by Thomasdezeeuw** [comment]
Sounds good @jkelleyrtp. Although last I check (I think version 9/10) WASI didn't allow for the creation of sockets, however that could have changed. In either case the various socket options could still be useful.

**Comment by LetsMelon** [comment]
> I believe WASI can be supported since their lib-c exposes sockets. I'd be interested in adding it.

I would be interested in giving it a try. However, after looking a bit through the codebase, I feel that it might be somewhat complicated.

> Sounds good @jkelleyrtp. Although last I check (I think version 9/10) WASI didn't allow for the creation of sockets, however that could have changed. In either case the various socket options could still be useful.

I _think_ that's still true, but there is an open and active [proposal](https://github.com/WebAssembly/wasi-sockets) to add the functionality to create sockets (https://github.com/WebAssembly/wasi-sockets/blob/f2ffc745086ec7ab168f1244f2b3ef0342bf9ddc/wit/tcp-create-socket.wit#L26 and https://github.com/WebAssembly/wasi-sockets/blob/f2ffc745086ec7ab168f1244f2b3ef0342bf9ddc/wit/udp-create-socket.wit#L26) which is currently in '[Phase 3 - Implementation Phase (CG + WG)](https://github.com/WebAssembly/WASI/blob/main/Proposals.md#phase-3---implementation-phase-cg--wg)'.

At the time of writing, WASIX has support via [`sock_open()`](https://wasix.org/docs/api-reference/wasix/sock_open) to create sockets.

---

I'm just a random user who stumbled upon this problem: `socket2` cannot be built with the target `wasm32-wasi`. I'm not a wasm/wasi wizard, so please correct me if I have made an error or overlooked something.

**Comment by Thomasdezeeuw** [comment]
Let's have the discussion in the other thread (https://github.com/rust-lang/socket2/issues/268#issuecomment-2059168732).
